FROM n8nio/n8n:latest

# Variables de entorno
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
ENV EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# Exponer puerto
EXPOSE 5678

# Comando de inicio corregido
CMD ["node", "/usr/local/bin/n8n"]